title: Site

columns:
  left:
    width: 2/3
    sections:
      pages:
        headline: Pages
        templates:
          - home
          - default
          - about
          - catalog
          - contact

  right: 
    width: 1/3
    sections:
    fields:
      companyName:
        type: text
        label: Company Name
      phone:
        type: tel
        label: Phone
        icon: phone
      whatsapp:
        type: tel
        label: Whatsapp
        icon: phone
      mail:
        type: email
        label: Email
      social:
        label: Follow
        type: structure
        fields:
          red:
            label: Social Network
            type: select
            options:
              fa-facebook-f: Facebook
              fa-twitter: Twitter
              fa-instagram: Instagram
              fa-linkedin-in: Linkedin
          enlace:
            label: Link
            type: url
